### ISSUE TITLE
Can this run the risk of web server timeouts?

### ISSUE THREAD

**Issue by mayurpande** [chirdeeptomar/fastapi-with-dask#1]
Hi, sorry more of a question then an issue, but lets say I submit a long running function to the dask cluster and it takes longer than the timeout for Nginx, even though it is async would this still suffer a timeout?

**Comment by chirdeeptomar** [comment]
Yes it would time out , for long running jobs, I would suggest to look into implementing server sent events and https://fastapi.tiangolo.com/tutorial/background-tasks/. I have not testing this scenario specially with Nginx as a proxy.

**Comment by mayurpande** [comment]
I ended up just using celery and polling it from the front-end.
